-- LINES 2 & 3 DELETE COMPANY DB IF IT ALREADY EXIST AND THEN CREATES IT
DROP DATABASE IF EXISTS company;
CREATE DATABASE company;

-- LINE 6 CONNECTS TO THE COMPANY DB
\c company;

-- CREATING DEPARTMENT, ROLE, AND EMPLOYEE TABLES IN THE COMPANY DB --
CREATE TABLE department (
  id SERIAL PRIMARY KEY,
  name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE role (
  id SERIAL PRIMARY KEY,
  job_title VARCHAR(30) UNIQUE NOT NULL,
  salary DECIMAL NOT NULL,
  department_id INTEGER NOT NULL,
  -- CONNECTING TO THE DEPARTMENT TABLE
  CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES department(id) ON DELETE CASCADE
);

CREATE TABLE employee (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    role_id INTEGER NOT NULL,
    manager_id INTEGER,
    -- CONNECTING TO THE ROLE TABLE
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE, -- IF THE RECORD IN PARENT TABLE IS DELETED, ANY CORRESPONDING RECORDS IN THE CHILD TABLE WILL ALSO BE AUTOMATICALLY DELETED
    -- CONNECTING MANAGER ID TO EMPLOYEE ID
    CONSTRAINT fk_manager FOREIGN KEY (manager_id) REFERENCES employee(id) ON DELETE SET NULL -- IF THE EMPLOYEE IS DELETED, THE VALUE WILL BE SET TO NULL
);

