-- LINES 2 & 3 DELETE COMPANY DB IF IT ALREADY EXIST AND THEN CREATES IT
DROP DATABASE IF EXISTS company;
CREATE DATABASE company;

-- LINE 6 CONNECTS TO THE COMPANY DB
\c company;

-- CREATING DEPARTMENT, ROLE, AND EMPLOYEE TABLES IN THE COMPANY DB --
CREATE TABLE department (
  id SERIAL PRIMARY KEY,
  name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE role (
  id SERIAL PRIMARY KEY,
  job_title VARCHAR(30) UNIQUE NOT NULL,
  salary DECIMAL NOT NULL,
  department_id INTEGER NOT NULL
);

CREATE TABLE employee (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    role_id INTEGER NOT NULL,
    manager_id INTEGER
);

